In [3]:

pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 1.4 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/12.6 MB 1.9 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.6 MB 2.1 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.6 MB 2.1 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/12.6 MB 2.4 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.6 MB 2.6 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.6 MB 2.6 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.6 MB 2.5 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.6 MB 2.5 MB/s eta 0:00:03
   ------------------- ----

In [4]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:

np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
print(arr)

[1 2 3]


In [12]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [16]:
np.arange(0, 12, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.random.rand(3, 2)

array([[0.6830607 , 0.40017218],
       [0.43748288, 0.78415082],
       [0.28240842, 0.38524693]])

In [20]:
np.random.randn(3, 2)

array([[-0.38294573,  0.86565487],
       [ 1.5884138 , -0.48021894],
       [ 0.51701457,  0.10382788]])

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
print(arr.shape)

(2, 3)


In [24]:
print(arr.ndim)

2


In [25]:
print(arr.size)

6


In [26]:
print(arr.dtype)


int64


In [27]:
arr = np.array([1, 2, 3, 4])


In [28]:
arr.sum()

np.int64(10)

In [29]:
a = np.array([1, 2, 3])

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [31]:
a + b

array([5, 7, 9])

In [32]:
a * b

array([ 4, 10, 18])

In [33]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [35]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [36]:
a * b

array([ 4, 10, 18])

In [38]:
arr = np.array([1, 2, 3, 4, 5])
